### ISSUE TITLE
关于任意用户名密码登陆的疑问

### ISSUE THREAD

**Issue by yichen115** [SPuerBRead/mqtts#1]
师傅，想问一下emqx embox_plugin_template任意用户名密码登陆这个是属于匿名登陆的一种吗，还是有什么其他安全问题，源码里的username和password是有什么特殊含义还是随便生成的，在网上搜了搜没搜到相关信息，我自己尝试，对于匿名登陆的确实可以随便指定个用户名和密码登录成功，谢谢师傅😊

**Comment by SPuerBRead** [comment]
> 师傅，想问一下emqx embox_plugin_template任意用户名密码登陆这个是属于匿名登陆的一种吗，还是有什么其他安全问题，源码里的username和password是有什么特殊含义还是随便生成的，在网上搜了搜没搜到相关信息，我自己尝试，对于匿名登陆的确实可以随便指定个用户名和密码登录成功，谢谢师傅😊

算是属于，具体存在问题的代码逻辑我也没有看，embox_plugin_template的问题是很久很久以前的版本的了，我测试的版本是3.0.1的时候，在这个版本如果emqx启用了embox_plugin_template这个插件，在allow_anonymous=false的情况下也是可以任意用户名密码登陆也可以空用户名密码登陆，本质就是匿名登陆，如果自己要测试的话

`docker run -d --name emqx -p 1883:1883 -p 8081:8081 -p 8083:8083 -p 8883:8883 -p 8084:8084 -p 18083:18083 emqx/emqx:v3.0.1`

然后把/opt/emqx/etc/emqx.conf的allow_anonymous改为false测试就可以

**Comment by yichen115** [comment]
谢谢师傅！另外，是不是应该是emqx_plugin_template😂我在releases和docker里都没看到embox
